import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.section}>
          <h1 className="display-large">
            Welcome to{" "}
            <a className="color-primary-text" href="https://nextjs.org">
              Next.js!
            </a>
          </h1>
        </section>

        <section className={styles.section}>
          <p className="body-large">
            Get started by editing{" "}
            <code className={styles.code}>pages/index.js</code>
          </p>
        </section>

        <section className={styles.section}>
          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className="card outlined">
              <h2 className="title">Documentation &rarr;</h2>
              <p className="subtitle">
                Find in-depth information about Next.js features and API.
              </p>
            </a>

            <a href="https://nextjs.org/learn" className="card outlined">
              <h2 className="title">Learn &rarr;</h2>
              <p className="subtitle">
                Learn about Next.js in an interactive course with quizzes!
              </p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className="card outlined"
            >
              <h2 className="title">Examples &rarr;</h2>
              <p className="subtitle">
                Discover and deploy boilerplate example Next.js projects.
              </p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className="card outlined"
            >
              <h2 className="title">Deploy &rarr;</h2>
              <p className="subtitle">
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </section>

        <section className={styles.section}>
          Built with{" "}
          <a
            className="color-primary-text"
            href="https://rodydavis.github.io/material-design-lite/components/"
          >
            Material Design Lite
          </a>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
