clone:
  depth: 1
cache:
  mount:
    - node_modules
build:
  image: crhym3/ci-image
  environment:
    - CHROME=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - WEBDRIVER=http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip
    - DISPLAY=:99
  commands:
    - npm install
    # build and unit test
    - gulp all
    - gulp mocha:closure
    # additional browser tests
    # do this after the build and unit tests to fail fast
    - Xvfb $DISPLAY &
    - curl -sSLo chrome.deb $CHROME && dpkg -i chrome.deb
    - curl -sSLo driver.zip $WEBDRIVER && unzip -q driver.zip -d /usr/bin
    - npm install babel-cli
    - ./node_modules/.bin/babel-node test/memory/test.js
#deploy:
#  bash:
#    when:
#      owner: google
#      branch: master
#    script:
#      - apt-get install -y python-openssl # gcloud deps for service accounts
#      - openssl aes-256-cbc -d -in .drone.p12.enc -out .drone.p12 -pass env:DRONE_PASS
#      - /gcloud/bin/gcloud components update -q gsutil
#      - /gcloud/bin/gcloud auth activate-service-account $$DRONE_ACCOUNT --key-file .drone.p12
#      - gulp publish:staging
