extends: google
globals:
  goog: false
env:
  browser: true
plugins:
  - tape
rules:
  max-len: [error, 120]
  no-new: warn
  quotes: [error, single, {"avoidEscape": true}]
  no-var: error
  curly: error
  no-floating-decimal: error
  no-unused-vars: error
  # Disabling jsdoc rules for the time being, but should be discussed as to whether or not this is
  # something we should add in. For closure compatibility, we can investigate using something like
  # https://github.com/angular/tsickle with .dts files.
  require-jsdoc: off
  valid-jsdoc: off
  prefer-const: error

  # tape rules
  # see: https://github.com/atabel/eslint-plugin-tape/blob/master/index.js
  tape/assertion-message:
    - off
    - always
  tape/max-asserts:
    - off
    - 5
  tape/no-identical-title: error
  tape/no-ignored-test-files: error
  tape/no-only-test: error
  tape/no-skip-assert: error
  tape/no-skip-test: error
  tape/no-statement-after-end: error
  tape/no-unknown-modifiers: error
  tape/test-ended: error
  tape/test-title:
    - error
    - if-multiple
  tape/use-t-well: error
  tape/use-t: error
  tape/use-test: error
