# Force TravisCI to run outside of a container
sudo: required
language: node_js
node_js:
  - node # stable
  - '4' # LTS
branches:
  only:
    - master
env:
  global:
    - SAUCE_USERNAME=material-sauce
    - SAUCE_ACCESS_KEY=5e3395b4-2026-48a4-82a0-35bc756a0d2b
addons:
  sauce_connect: true
