name: Demo

on:
  push:
    branches: [dev]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: cd docsite && npm i

      - name: Build
        run: |
          cd docsite && npm run build
      - name: Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docsite/dist
